CREATE TABLE Employee (
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Age INT NOT NULL,
	[Adress] NVARCHAR(MAX),
);

CREATE TABLE Customers (
	Id INT PRIMARY KEY IDENTITY,
	EmployeeId INT FOREIGN KEY REFERENCES Employee(Id)
);

CREATE TABLE Admins (
	Id INT PRIMARY KEY IDENTITY,
	EmployeeId INT FOREIGN KEY REFERENCES Employee(Id)
);
GO


CREATE TABLE OilType (
	Id INT PRIMARY KEY IDENTITY,
	[Type] NVARCHAR(100)
)
CREATE TABLE Manufacturer (
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100)
)
CREATE TABLE Viscosity (
	Id INT PRIMARY KEY IDENTITY,
	[Type] NVARCHAR(100)
)
CREATE TABLE Composition (
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100)
)
CREATE TABLE ACEA (
	Id INT PRIMARY KEY IDENTITY,
	[Description] NVARCHAR(5)
)
CREATE TABLE API (
	Id INT PRIMARY KEY IDENTITY,
	[Description] NVARCHAR(5)
)
CREATE TABLE [OEM] (
	Id INT PRIMARY KEY IDENTITY,
	[Description] NVARCHAR(5)
)
CREATE TABLE Oil (
	Id INT PRIMARY KEY IDENTITY,
	OilType INT FOREIGN KEY REFERENCES OilType(Id) NOT NULL,
	Manufacturer INT FOREIGN KEY REFERENCES Manufacturer(Id)  NOT NULL,
	Viscosity INT FOREIGN KEY REFERENCES Viscosity(Id)  NOT NULL,
	Composition INT FOREIGN KEY REFERENCES Composition(Id)  NOT NULL,
	ACEA INT FOREIGN KEY REFERENCES ACEA(Id)  NOT NULL,
	API INT FOREIGN KEY REFERENCES API(Id)  NOT NULL,
	[OEM] INT FOREIGN KEY REFERENCES [OEM](Id)  NOT NULL,
);
GO


CREATE TABLE AccumulatorManufacturer (
	Id INT PRIMARY KEY IDENTITY,
	Manufacturer NVARCHAR(100)
)
CREATE TABLE Voltage (
	Id INT PRIMARY KEY IDENTITY,
	Voltage INT
)
CREATE TABLE BatteryCapacity (
	Id INT PRIMARY KEY IDENTITY,
	Capacity INT
)
CREATE TABLE AccumulatorLength (
	Id INT PRIMARY KEY IDENTITY,
	[Length] INT
)
CREATE TABLE AccumulatorWidth (
	Id INT PRIMARY KEY IDENTITY,
	Width INT
)
CREATE TABLE AccumulatorHeigh (
	Id INT PRIMARY KEY IDENTITY,
	Heigh INT
)
CREATE TABLE AccumulatorSeries (
	Id INT PRIMARY KEY IDENTITY,
	Series NVARCHAR(50)
)
CREATE TABLE Accumulator (
	Id INT PRIMARY KEY IDENTITY,
	Manufacturer INT FOREIGN KEY REFERENCES AccumulatorManufacturer(Id)  NOT NULL,
	Voltage INT FOREIGN KEY REFERENCES Voltage(Id) NOT NULL,
	BatteryCapacity INT FOREIGN KEY REFERENCES BatteryCapacity(Id) NOT NULL,
	AccumulatorLength INT FOREIGN KEY REFERENCES AccumulatorLength(Id) NOT NULL,
	AccumulatorWidth INT FOREIGN KEY REFERENCES AccumulatorWidth(Id) NOT NULL,
	AccumulatorHeigh INT FOREIGN KEY REFERENCES AccumulatorHeigh(Id) NOT NULL,
	AccumulatorSeries INT FOREIGN KEY REFERENCES AccumulatorSeries(Id) NOT NULL
)
GO


CREATE TABLE TiresRadius (
	Id INT PRIMARY KEY IDENTITY,
	Radius INT
)
CREATE TABLE TiresDiameter (
	Id INT PRIMARY KEY IDENTITY,
	Diameter INT
)
CREATE TABLE LoadIndex (
	Id INT PRIMARY KEY IDENTITY,
	[Load] INT
)
CREATE TABLE SpeedIndex (
	Id INT PRIMARY KEY IDENTITY,
	Speed INT
)
CREATE TABLE TiresWidth (
	Id INT PRIMARY KEY IDENTITY,
	Width INT
)
CREATE TABLE TiresHeight (
	Id INT PRIMARY KEY IDENTITY,
	Height INT
)
CREATE TABLE Tires (
	Id INT PRIMARY KEY IDENTITY,
	TiresRadius INT FOREIGN KEY REFERENCES TiresRadius(Id) NOT NULL,
	TiresDiameter INT FOREIGN KEY REFERENCES TiresDiameter(Id) NOT NULL,
	LoadIndex INT FOREIGN KEY REFERENCES LoadIndex(Id) NOT NULL,
	SpeedIndex INT FOREIGN KEY REFERENCES SpeedIndex(Id) NOT NULL,
	TiresWidth INT FOREIGN KEY REFERENCES TiresWidth(Id) NOT NULL,
	TiresHeight INT FOREIGN KEY REFERENCES TiresHeight(Id) NOT NULL
);
GO


CREATE TABLE DisksWidth (
	Id INT PRIMARY KEY IDENTITY,
	Width INT
)
CREATE TABLE DisksDiameter (
	Id INT PRIMARY KEY IDENTITY,
	Diameter INT
)
CREATE TABLE DiameterOfTheCenteralHole (
	Id INT PRIMARY KEY IDENTITY,
	Diameter INT
)
CREATE TABLE DepartureET (
	Id INT PRIMARY KEY IDENTITY,
	ET INT
)
CREATE TABLE NumberOfMountingHoles (
	Id INT PRIMARY KEY IDENTITY,
	Number INT
)
CREATE TABLE Disks(
	Id INT PRIMARY KEY IDENTITY,
	DisksWidth INT FOREIGN KEY REFERENCES DisksWidth(Id) NOT NULL,
	DisksDiameter INT FOREIGN KEY REFERENCES DisksDiameter(Id) NOT NULL,
	DiameterOfTheCenteralHole INT FOREIGN KEY REFERENCES DiameterOfTheCenteralHole(Id) NOT NULL,
	DepartureET INT FOREIGN KEY REFERENCES DepartureET(Id) NOT NULL,
	NumberOfMountingHoles INT FOREIGN KEY REFERENCES NumberOfMountingHoles(Id) NOT NULL,
)
GO
