CREATE TABLE Employee (
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Age INT NOT NULL,
	[Address] NVARCHAR(MAX)
);

CREATE TABLE Customers (
	Id INT PRIMARY KEY IDENTITY,
	EmployeeId INT FOREIGN KEY REFERENCES Employee(Id)
);

CREATE TABLE Admins (
	Id INT PRIMARY KEY IDENTITY,
	EmployeeId INT FOREIGN KEY REFERENCES Employee(Id)
);
GO


CREATE TABLE OilType (
	Id INT PRIMARY KEY IDENTITY,
	[Type] NVARCHAR(100)
)
CREATE TABLE Manufacturer (
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100)
)
CREATE TABLE Viscosity (
	Id INT PRIMARY KEY IDENTITY,
	[Type] NVARCHAR(100)
)
CREATE TABLE Composition (
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100)
)
CREATE TABLE ACEA (
	Id INT PRIMARY KEY IDENTITY,
	[Description] NVARCHAR(5)
)
CREATE TABLE API (
	Id INT PRIMARY KEY IDENTITY,
	[Description] NVARCHAR(5)
)
CREATE TABLE [OEM] (
	Id INT PRIMARY KEY IDENTITY,
	[Description] NVARCHAR(5)
)
CREATE TABLE Oil (
	Id INT PRIMARY KEY IDENTITY,
	OilTypeId INT FOREIGN KEY REFERENCES OilType(Id) NOT NULL,
	ManufacturerId INT FOREIGN KEY REFERENCES Manufacturer(Id)  NOT NULL,
	ViscosityId INT FOREIGN KEY REFERENCES Viscosity(Id)  NOT NULL,
	CompositionId INT FOREIGN KEY REFERENCES Composition(Id)  NOT NULL,
	ACEA_Id INT FOREIGN KEY REFERENCES ACEA(Id)  NOT NULL,
	API_Id INT FOREIGN KEY REFERENCES API(Id)  NOT NULL,
	OEM_Id INT FOREIGN KEY REFERENCES [OEM](Id)  NOT NULL,
);
GO


CREATE TABLE AccumulatorManufacturer (
	Id INT PRIMARY KEY IDENTITY,
	Manufacturer NVARCHAR(100)
)
CREATE TABLE Voltage (
	Id INT PRIMARY KEY IDENTITY,
	Voltage INT
)
CREATE TABLE BatteryCapacity (
	Id INT PRIMARY KEY IDENTITY,
	Capacity INT
)
CREATE TABLE AccumulatorLength (
	Id INT PRIMARY KEY IDENTITY,
	[Length] INT
)
CREATE TABLE AccumulatorWidth (
	Id INT PRIMARY KEY IDENTITY,
	Width INT
)
CREATE TABLE AccumulatorHeight (
	Id INT PRIMARY KEY IDENTITY,
	Height INT
)
CREATE TABLE AccumulatorSeries (
	Id INT PRIMARY KEY IDENTITY,
	Series NVARCHAR(50)
)
CREATE TABLE Accumulator (
	Id INT PRIMARY KEY IDENTITY,
	ManufacturerId INT FOREIGN KEY REFERENCES AccumulatorManufacturer(Id)  NOT NULL,
	VoltageId INT FOREIGN KEY REFERENCES Voltage(Id) NOT NULL,
	BatteryCapacityId INT FOREIGN KEY REFERENCES BatteryCapacity(Id) NOT NULL,
	AccumulatorLengthId INT FOREIGN KEY REFERENCES AccumulatorLength(Id) NOT NULL,
	AccumulatorWidthId INT FOREIGN KEY REFERENCES AccumulatorWidth(Id) NOT NULL,
	AccumulatorHeightId INT FOREIGN KEY REFERENCES AccumulatorHeight(Id) NOT NULL,
	AccumulatorSeriesId INT FOREIGN KEY REFERENCES AccumulatorSeries(Id) NOT NULL
)
GO


CREATE TABLE TiresRadius (
	Id INT PRIMARY KEY IDENTITY,
	Radius INT
)
CREATE TABLE TiresDiameter (
	Id INT PRIMARY KEY IDENTITY,
	Diameter INT
)
CREATE TABLE LoadIndex (
	Id INT PRIMARY KEY IDENTITY,
	[Load] INT
)
CREATE TABLE SpeedIndex (
	Id INT PRIMARY KEY IDENTITY,
	Speed INT
)
CREATE TABLE TiresWidth (
	Id INT PRIMARY KEY IDENTITY,
	Width INT
)
CREATE TABLE TiresHeight (
	Id INT PRIMARY KEY IDENTITY,
	Height INT
)
CREATE TABLE Tires (
	Id INT PRIMARY KEY IDENTITY,
	TiresRadiusId INT FOREIGN KEY REFERENCES TiresRadius(Id) NOT NULL,
	TiresDiameterId INT FOREIGN KEY REFERENCES TiresDiameter(Id) NOT NULL,
	LoadIndexId INT FOREIGN KEY REFERENCES LoadIndex(Id) NOT NULL,
	SpeedIndexId INT FOREIGN KEY REFERENCES SpeedIndex(Id) NOT NULL,
	TiresWidthId INT FOREIGN KEY REFERENCES TiresWidth(Id) NOT NULL,
	TiresHeightId INT FOREIGN KEY REFERENCES TiresHeight(Id) NOT NULL
);
GO


CREATE TABLE DisksWidth (
	Id INT PRIMARY KEY IDENTITY,
	Width INT
)
CREATE TABLE DisksDiameter (
	Id INT PRIMARY KEY IDENTITY,
	Diameter INT
)
CREATE TABLE DiameterOfTheCenteralHole (
	Id INT PRIMARY KEY IDENTITY,
	Diameter INT
)
CREATE TABLE DepartureET (
	Id INT PRIMARY KEY IDENTITY,
	ET INT
)
CREATE TABLE NumberOfMountingHoles (
	Id INT PRIMARY KEY IDENTITY,
	Number INT
)
CREATE TABLE Disks(
	Id INT PRIMARY KEY IDENTITY,
	DisksWidthId INT FOREIGN KEY REFERENCES DisksWidth(Id) NOT NULL,
	DisksDiameterId INT FOREIGN KEY REFERENCES DisksDiameter(Id) NOT NULL,
	DiameterOfTheCenteralHoleId INT FOREIGN KEY REFERENCES DiameterOfTheCenteralHole(Id) NOT NULL,
	DepartureET_Id INT FOREIGN KEY REFERENCES DepartureET(Id) NOT NULL,
	NumberOfMountingHolesId INT FOREIGN KEY REFERENCES NumberOfMountingHoles(Id) NOT NULL,
)
GO
